# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeView = QtWidgets.QTreeView(self.splitter)
        self.treeView.setObjectName("treeView")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayoutMenu = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayoutMenu.setObjectName("verticalLayoutMenu")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonPickup = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonPickup.setObjectName("pushButtonPickup")
        self.verticalLayout.addWidget(self.pushButtonPickup)
        self.verticalLayoutMenu.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tabActiveChart = QtWidgets.QWidget()
        self.tabActiveChart.setObjectName("tabActiveChart")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabActiveChart)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonApplyChart = QtWidgets.QPushButton(self.tabActiveChart)
        self.pushButtonApplyChart.setObjectName("pushButtonApplyChart")
        self.verticalLayout_3.addWidget(self.pushButtonApplyChart)
        self.tabWidget.addTab(self.tabActiveChart, "")
        self.tabActiveBook = QtWidgets.QWidget()
        self.tabActiveBook.setObjectName("tabActiveBook")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabActiveBook)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBoxTarget = QtWidgets.QComboBox(self.tabActiveBook)
        self.comboBoxTarget.setObjectName("comboBoxTarget")
        self.verticalLayout_4.addWidget(self.comboBoxTarget)
        self.comboBoxType = QtWidgets.QComboBox(self.tabActiveBook)
        self.comboBoxType.setObjectName("comboBoxType")
        self.verticalLayout_4.addWidget(self.comboBoxType)
        self.pushButtonApplyBook = QtWidgets.QPushButton(self.tabActiveBook)
        self.pushButtonApplyBook.setObjectName("pushButtonApplyBook")
        self.verticalLayout_4.addWidget(self.pushButtonApplyBook)
        self.tabWidget.addTab(self.tabActiveBook, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayoutMenu.addWidget(self.groupBox_2)
        self.verticalLayout_5.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 24))
        self.menubar.setObjectName("menubar")
        self.menuStyles = QtWidgets.QMenu(self.menubar)
        self.menuStyles.setObjectName("menuStyles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewStyle = QtWidgets.QAction(MainWindow)
        self.actionNewStyle.setObjectName("actionNewStyle")
        self.actionUpStyle = QtWidgets.QAction(MainWindow)
        self.actionUpStyle.setObjectName("actionUpStyle")
        self.actionDownStyle = QtWidgets.QAction(MainWindow)
        self.actionDownStyle.setObjectName("actionDownStyle")
        self.actionRemoveStyle = QtWidgets.QAction(MainWindow)
        self.actionRemoveStyle.setObjectName("actionRemoveStyle")
        self.actionReplicate = QtWidgets.QAction(MainWindow)
        self.actionReplicate.setObjectName("actionReplicate")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuStyles.addAction(self.actionNewStyle)
        self.menuStyles.addAction(self.actionUpStyle)
        self.menuStyles.addAction(self.actionDownStyle)
        self.menuStyles.addAction(self.actionRemoveStyle)
        self.menuStyles.addAction(self.actionReplicate)
        self.menuStyles.addSeparator()
        self.menuStyles.addAction(self.actionLoad)
        self.menuStyles.addAction(self.actionSave)
        self.menubar.addAction(self.menuStyles.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "xlpicker"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Pickup style"))
        self.pushButtonPickup.setText(_translate("MainWindow", "from ActiveChart"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Select target to"))
        self.pushButtonApplyChart.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActiveChart), _translate("MainWindow", "ActiveChart"))
        self.pushButtonApplyBook.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActiveBook), _translate("MainWindow", "ActiveBook"))
        self.menuStyles.setTitle(_translate("MainWindow", "&Styles"))
        self.actionNewStyle.setText(_translate("MainWindow", "New"))
        self.actionUpStyle.setText(_translate("MainWindow", "Up"))
        self.actionDownStyle.setText(_translate("MainWindow", "Down"))
        self.actionRemoveStyle.setText(_translate("MainWindow", "Remove"))
        self.actionReplicate.setText(_translate("MainWindow", "Replicate"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

import resource_rc
